// <auto-generated />
using System;
using Counter.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Counter.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241029205214_EntityModelCreation")]
    partial class EntityModelCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Counter.Shared.DTOs.CountRequestDTO", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Akim")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("OlcumZamani")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("SeriNumarasi")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("SonEndeks")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Voltaj")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("UUID");

                    b.ToTable("Counters", (string)null);
                });

            modelBuilder.Entity("Counter.Shared.DTOs.ReportRequestDTO", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Durum")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("UUID");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Counter.Shared.DTOs.ReportRequestDTO", b =>
                {
                    b.OwnsOne("Counter.Shared.DTOs.Icerik", "Icerik", b1 =>
                        {
                            b1.Property<Guid>("ReportRequestDTOUUID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Akim")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Akim");

                            b1.Property<DateTime>("OlcumZamani")
                                .HasColumnType("datetime2(0)")
                                .HasColumnName("OlcumZamani");

                            b1.Property<decimal>("SonEndeks")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("SonEndeks");

                            b1.Property<decimal>("Voltaj")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Voltaj");

                            b1.HasKey("ReportRequestDTOUUID");

                            b1.ToTable("Reports");

                            b1.WithOwner()
                                .HasForeignKey("ReportRequestDTOUUID");
                        });

                    b.Navigation("Icerik");
                });
#pragma warning restore 612, 618
        }
    }
}
