// <auto-generated />
using System;
using Counter.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Counter.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Counter.Shared.DTOs.CountDTO", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Akim")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("OlcumZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriNumarasi")
                        .HasColumnType("text");

                    b.Property<double>("SonEndeks")
                        .HasColumnType("double precision");

                    b.Property<double>("Voltaj")
                        .HasColumnType("double precision");

                    b.HasKey("UUID");

                    b.ToTable("Counters", (string)null);
                });

            modelBuilder.Entity("Counter.Shared.DTOs.ReportDTO", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Durum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UUID");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Counter.Shared.DTOs.ReportDTO", b =>
                {
                    b.OwnsOne("Counter.Shared.DTOs.Icerik", "Icerik", b1 =>
                        {
                            b1.Property<Guid>("ReportDTOUUID")
                                .HasColumnType("uuid");

                            b1.Property<double>("Akim")
                                .HasColumnType("double precision");

                            b1.Property<DateTime>("OlcumZamani")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("SonEndeks")
                                .HasColumnType("integer");

                            b1.Property<double>("Voltaj")
                                .HasColumnType("double precision");

                            b1.HasKey("ReportDTOUUID");

                            b1.ToTable("Reports");

                            b1.WithOwner()
                                .HasForeignKey("ReportDTOUUID");
                        });

                    b.Navigation("Icerik");
                });
#pragma warning restore 612, 618
        }
    }
}
